name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '^3.6.0'


dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.2
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  intl: ^0.20.1
  pie_chart: ^5.4.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
# add more fonts in the future

